package mod.amalgam.init;

import java.util.ArrayList;
import java.util.HashMap;

import mod.amalgam.blocks.BlockCarbonite;
import mod.amalgam.blocks.BlockDrainBlock;
import mod.amalgam.blocks.BlockDrainLily;
import mod.amalgam.blocks.BlockGemSeed;
import mod.amalgam.blocks.BlockWailingStone;
import net.minecraft.block.Block;
import net.minecraft.item.Item;
import net.minecraft.item.ItemBlock;
import net.minecraft.util.ResourceLocation;
import net.minecraftforge.event.RegistryEvent;
import net.minecraftforge.oredict.OreDictionary;

public class AmBlocks {
	public static final HashMap<String, Item> DICTS = new HashMap<String, Item>();
	public static final HashMap<Item, String[]> META = new HashMap<Item, String[]>();
	public static final ArrayList<Item> ITEMS = new ArrayList<Item>();
	
	public static final BlockWailingStone WAILING_STONE = new BlockWailingStone();
	public static final BlockGemSeed GEM_SEED = new BlockGemSeed();
	public static final BlockDrainLily DRAIN_LILY = new BlockDrainLily();
	
	public static final BlockDrainBlock LIGHT_PURPLE_DRAIN_BLOCK = new BlockDrainBlock(false, "purple", 0);
	public static final BlockDrainBlock BANDED_PURPLE_DRAIN_BLOCK = new BlockDrainBlock(false, "purple", 1);
	public static final BlockDrainBlock DARK_PURPLE_DRAIN_BLOCK = new BlockDrainBlock(false, "purple", 2);
	public static final BlockDrainBlock ERODED_PURPLE_DRAIN_BLOCK = new BlockDrainBlock(true, "purple", 3);
	public static final BlockDrainBlock LIGHT_ORANGE_DRAIN_BLOCK = new BlockDrainBlock(false, "orange", 0);
	public static final BlockDrainBlock BANDED_ORANGE_DRAIN_BLOCK = new BlockDrainBlock(false, "orange", 1);
	public static final BlockDrainBlock DARK_ORANGE_DRAIN_BLOCK = new BlockDrainBlock(false, "orange", 2);
	public static final BlockDrainBlock ERODED_ORANGE_DRAIN_BLOCK = new BlockDrainBlock(true, "orange", 3);
	public static final BlockDrainBlock LIGHT_BLUE_DRAIN_BLOCK = new BlockDrainBlock(false, "blue", 0);
	public static final BlockDrainBlock BANDED_BLUE_DRAIN_BLOCK = new BlockDrainBlock(false, "blue", 1);
	public static final BlockDrainBlock DARK_BLUE_DRAIN_BLOCK = new BlockDrainBlock(false, "blue", 2);
	public static final BlockDrainBlock ERODED_BLUE_DRAIN_BLOCK = new BlockDrainBlock(true, "blue", 3);
	public static final BlockDrainBlock LIGHT_RED_DRAIN_BLOCK = new BlockDrainBlock(false, "red", 0);
	public static final BlockDrainBlock BANDED_RED_DRAIN_BLOCK = new BlockDrainBlock(false, "red", 1);
	public static final BlockDrainBlock DARK_RED_DRAIN_BLOCK = new BlockDrainBlock(false, "red", 2);
	public static final BlockDrainBlock ERODED_RED_DRAIN_BLOCK = new BlockDrainBlock(true, "red", 3);

	public static final BlockCarbonite WHITE_CARBONITE = new BlockCarbonite(AmGems.BASIC_WHITE);
	public static final BlockCarbonite WHITE_CARBONITE_OFF = new BlockCarbonite(false, AmGems.BASIC_WHITE);
	public static final BlockCarbonite WHITE_CARBONITE_ON = new BlockCarbonite(true, AmGems.BASIC_WHITE);
	public static final BlockCarbonite WHITE_DECORATIVE_CARBONITE = new BlockCarbonite(AmGems.BASIC_WHITE);
	public static final BlockCarbonite ORANGE_CARBONITE = new BlockCarbonite(AmGems.BASIC_ORANGE);
	public static final BlockCarbonite ORANGE_CARBONITE_OFF = new BlockCarbonite(false, AmGems.BASIC_ORANGE);
	public static final BlockCarbonite ORANGE_CARBONITE_ON = new BlockCarbonite(true, AmGems.BASIC_ORANGE);
	public static final BlockCarbonite ORANGE_DECORATIVE_CARBONITE = new BlockCarbonite(AmGems.BASIC_ORANGE);
	public static final BlockCarbonite MAGENTA_CARBONITE = new BlockCarbonite(AmGems.BASIC_MAGENTA);
	public static final BlockCarbonite MAGENTA_CARBONITE_OFF = new BlockCarbonite(false, AmGems.BASIC_MAGENTA);
	public static final BlockCarbonite MAGENTA_CARBONITE_ON = new BlockCarbonite(true, AmGems.BASIC_MAGENTA);
	public static final BlockCarbonite MAGENTA_DECORATIVE_CARBONITE = new BlockCarbonite(AmGems.BASIC_MAGENTA);
	public static final BlockCarbonite LIGHT_BLUE_CARBONITE = new BlockCarbonite(AmGems.BASIC_LIGHT_BLUE);
	public static final BlockCarbonite LIGHT_BLUE_CARBONITE_OFF = new BlockCarbonite(false, AmGems.BASIC_LIGHT_BLUE);
	public static final BlockCarbonite LIGHT_BLUE_CARBONITE_ON = new BlockCarbonite(true, AmGems.BASIC_LIGHT_BLUE);
	public static final BlockCarbonite LIGHT_BLUE_DECORATIVE_CARBONITE = new BlockCarbonite(AmGems.BASIC_LIGHT_BLUE);
	public static final BlockCarbonite YELLOW_CARBONITE = new BlockCarbonite(AmGems.BASIC_YELLOW);
	public static final BlockCarbonite YELLOW_CARBONITE_OFF = new BlockCarbonite(false, AmGems.BASIC_YELLOW);
	public static final BlockCarbonite YELLOW_CARBONITE_ON = new BlockCarbonite(true, AmGems.BASIC_YELLOW);
	public static final BlockCarbonite YELLOW_DECORATIVE_CARBONITE = new BlockCarbonite(AmGems.BASIC_YELLOW);
	public static final BlockCarbonite LIME_CARBONITE = new BlockCarbonite(AmGems.BASIC_LIME);
	public static final BlockCarbonite LIME_CARBONITE_OFF = new BlockCarbonite(false, AmGems.BASIC_LIME);
	public static final BlockCarbonite LIME_CARBONITE_ON = new BlockCarbonite(true, AmGems.BASIC_LIME);
	public static final BlockCarbonite LIME_DECORATIVE_CARBONITE = new BlockCarbonite(AmGems.BASIC_LIME);
	public static final BlockCarbonite PINK_CARBONITE = new BlockCarbonite(AmGems.BASIC_PINK);
	public static final BlockCarbonite PINK_CARBONITE_OFF = new BlockCarbonite(false, AmGems.BASIC_PINK);
	public static final BlockCarbonite PINK_CARBONITE_ON = new BlockCarbonite(true, AmGems.BASIC_PINK);
	public static final BlockCarbonite PINK_DECORATIVE_CARBONITE = new BlockCarbonite(AmGems.BASIC_PINK);
	public static final BlockCarbonite GRAY_CARBONITE = new BlockCarbonite(AmGems.BASIC_GRAY);
	public static final BlockCarbonite GRAY_CARBONITE_OFF = new BlockCarbonite(false, AmGems.BASIC_GRAY);
	public static final BlockCarbonite GRAY_CARBONITE_ON = new BlockCarbonite(true, AmGems.BASIC_GRAY);
	public static final BlockCarbonite GRAY_DECORATIVE_CARBONITE = new BlockCarbonite(AmGems.BASIC_GRAY);
	public static final BlockCarbonite SILVER_CARBONITE = new BlockCarbonite(AmGems.BASIC_SILVER);
	public static final BlockCarbonite SILVER_CARBONITE_OFF = new BlockCarbonite(false, AmGems.BASIC_SILVER);
	public static final BlockCarbonite SILVER_CARBONITE_ON = new BlockCarbonite(true, AmGems.BASIC_SILVER);
	public static final BlockCarbonite SILVER_DECORATIVE_CARBONITE = new BlockCarbonite(AmGems.BASIC_SILVER);
	public static final BlockCarbonite CYAN_CARBONITE = new BlockCarbonite(AmGems.BASIC_CYAN);
	public static final BlockCarbonite CYAN_CARBONITE_OFF = new BlockCarbonite(false, AmGems.BASIC_CYAN);
	public static final BlockCarbonite CYAN_CARBONITE_ON = new BlockCarbonite(true, AmGems.BASIC_CYAN);
	public static final BlockCarbonite CYAN_DECORATIVE_CARBONITE = new BlockCarbonite(AmGems.BASIC_CYAN);
	public static final BlockCarbonite PURPLE_CARBONITE = new BlockCarbonite(AmGems.BASIC_PURPLE);
	public static final BlockCarbonite PURPLE_CARBONITE_OFF = new BlockCarbonite(false, AmGems.BASIC_PURPLE);
	public static final BlockCarbonite PURPLE_CARBONITE_ON = new BlockCarbonite(true, AmGems.BASIC_PURPLE);
	public static final BlockCarbonite PURPLE_DECORATIVE_CARBONITE = new BlockCarbonite(AmGems.BASIC_PURPLE);
	public static final BlockCarbonite BLUE_CARBONITE = new BlockCarbonite(AmGems.BASIC_BLUE);
	public static final BlockCarbonite BLUE_CARBONITE_OFF = new BlockCarbonite(false, AmGems.BASIC_BLUE);
	public static final BlockCarbonite BLUE_CARBONITE_ON = new BlockCarbonite(true, AmGems.BASIC_BLUE);
	public static final BlockCarbonite BLUE_DECORATIVE_CARBONITE = new BlockCarbonite(AmGems.BASIC_BLUE);
	public static final BlockCarbonite BROWN_CARBONITE = new BlockCarbonite(AmGems.BASIC_BROWN);
	public static final BlockCarbonite BROWN_CARBONITE_OFF = new BlockCarbonite(false, AmGems.BASIC_BROWN);
	public static final BlockCarbonite BROWN_CARBONITE_ON = new BlockCarbonite(true, AmGems.BASIC_BROWN);
	public static final BlockCarbonite BROWN_DECORATIVE_CARBONITE = new BlockCarbonite(AmGems.BASIC_BROWN);
	public static final BlockCarbonite GREEN_CARBONITE = new BlockCarbonite(AmGems.BASIC_GREEN);
	public static final BlockCarbonite GREEN_CARBONITE_OFF = new BlockCarbonite(false, AmGems.BASIC_GREEN);
	public static final BlockCarbonite GREEN_CARBONITE_ON = new BlockCarbonite(true, AmGems.BASIC_GREEN);
	public static final BlockCarbonite GREEN_DECORATIVE_CARBONITE = new BlockCarbonite(AmGems.BASIC_GREEN);
	public static final BlockCarbonite RED_CARBONITE = new BlockCarbonite(AmGems.BASIC_RED);
	public static final BlockCarbonite RED_CARBONITE_OFF = new BlockCarbonite(false, AmGems.BASIC_RED);
	public static final BlockCarbonite RED_CARBONITE_ON = new BlockCarbonite(true, AmGems.BASIC_RED);
	public static final BlockCarbonite RED_DECORATIVE_CARBONITE = new BlockCarbonite(AmGems.BASIC_RED);
	public static final BlockCarbonite BLACK_CARBONITE = new BlockCarbonite(AmGems.BASIC_BLACK);
	public static final BlockCarbonite BLACK_CARBONITE_OFF = new BlockCarbonite(false, AmGems.BASIC_BLACK);
	public static final BlockCarbonite BLACK_CARBONITE_ON = new BlockCarbonite(true, AmGems.BASIC_BLACK);
	public static final BlockCarbonite BLACK_DECORATIVE_CARBONITE = new BlockCarbonite(AmGems.BASIC_BLACK);
	
	public static void register(RegistryEvent.Register<Block> event) {
		registerBlock(WAILING_STONE, new ResourceLocation("amalgam:wailing_stone"), event);
		registerBlock(GEM_SEED, new ResourceLocation("amalgam:gem_seed"), event);
		registerBlock(DRAIN_LILY, new ResourceLocation("amalgam:drain_lily"), event);
		registerBlock(LIGHT_PURPLE_DRAIN_BLOCK, new ResourceLocation("amalgam:light_purple_drain_block"), event);
		registerBlock(BANDED_PURPLE_DRAIN_BLOCK, new ResourceLocation("amalgam:banded_purple_drain_block"), event);
		registerBlock(DARK_PURPLE_DRAIN_BLOCK, new ResourceLocation("amalgam:dark_purple_drain_block"), event);
		registerBlock(ERODED_PURPLE_DRAIN_BLOCK, new ResourceLocation("amalgam:eroded_purple_drain_block"), event);
		registerBlock(LIGHT_ORANGE_DRAIN_BLOCK, new ResourceLocation("amalgam:light_orange_drain_block"), event);
		registerBlock(BANDED_ORANGE_DRAIN_BLOCK, new ResourceLocation("amalgam:banded_orange_drain_block"), event);
		registerBlock(DARK_ORANGE_DRAIN_BLOCK, new ResourceLocation("amalgam:dark_orange_drain_block"), event);
		registerBlock(ERODED_ORANGE_DRAIN_BLOCK, new ResourceLocation("amalgam:eroded_orange_drain_block"), event);
		registerBlock(LIGHT_BLUE_DRAIN_BLOCK, new ResourceLocation("amalgam:light_blue_drain_block"), event);
		registerBlock(BANDED_BLUE_DRAIN_BLOCK, new ResourceLocation("amalgam:banded_blue_drain_block"), event);
		registerBlock(DARK_BLUE_DRAIN_BLOCK, new ResourceLocation("amalgam:dark_blue_drain_block"), event);
		registerBlock(ERODED_BLUE_DRAIN_BLOCK, new ResourceLocation("amalgam:eroded_blue_drain_block"), event);
		registerBlock(LIGHT_RED_DRAIN_BLOCK, new ResourceLocation("amalgam:light_red_drain_block"), event);
		registerBlock(BANDED_RED_DRAIN_BLOCK, new ResourceLocation("amalgam:banded_red_drain_block"), event);
		registerBlock(DARK_RED_DRAIN_BLOCK, new ResourceLocation("amalgam:dark_red_drain_block"), event);
		registerBlock(ERODED_RED_DRAIN_BLOCK, new ResourceLocation("amalgam:eroded_red_drain_block"), event);
		registerBlock(WHITE_CARBONITE, new ResourceLocation("amalgam:white_carbonite"), event);
		registerBlock(WHITE_CARBONITE_OFF, new ResourceLocation("amalgam:white_carbonite_off"), event);
		registerBlock(WHITE_CARBONITE_ON, new ResourceLocation("amalgam:white_carbonite_on"), event);
		registerBlock(WHITE_DECORATIVE_CARBONITE, new ResourceLocation("amalgam:white_decorative_carbonite"), event);
		registerBlock(ORANGE_CARBONITE, new ResourceLocation("amalgam:orange_carbonite"), event);
		registerBlock(ORANGE_CARBONITE_OFF, new ResourceLocation("amalgam:orange_carbonite_off"), event);
		registerBlock(ORANGE_CARBONITE_ON, new ResourceLocation("amalgam:orange_carbonite_on"), event);
		registerBlock(ORANGE_DECORATIVE_CARBONITE, new ResourceLocation("amalgam:orange_decorative_carbonite"), event);
		registerBlock(MAGENTA_CARBONITE, new ResourceLocation("amalgam:magenta_carbonite"), event);
		registerBlock(MAGENTA_CARBONITE_OFF, new ResourceLocation("amalgam:magenta_carbonite_off"), event);
		registerBlock(MAGENTA_CARBONITE_ON, new ResourceLocation("amalgam:magenta_carbonite_on"), event);
		registerBlock(MAGENTA_DECORATIVE_CARBONITE, new ResourceLocation("amalgam:magenta_decorative_carbonite"), event);
		registerBlock(LIGHT_BLUE_CARBONITE, new ResourceLocation("amalgam:light_blue_carbonite"), event);
		registerBlock(LIGHT_BLUE_CARBONITE_OFF, new ResourceLocation("amalgam:light_blue_carbonite_off"), event);
		registerBlock(LIGHT_BLUE_CARBONITE_ON, new ResourceLocation("amalgam:light_blue_carbonite_on"), event);
		registerBlock(LIGHT_BLUE_DECORATIVE_CARBONITE, new ResourceLocation("amalgam:light_blue_decorative_carbonite"), event);
		registerBlock(YELLOW_CARBONITE, new ResourceLocation("amalgam:yellow_carbonite"), event);
		registerBlock(YELLOW_CARBONITE_OFF, new ResourceLocation("amalgam:yellow_carbonite_off"), event);
		registerBlock(YELLOW_CARBONITE_ON, new ResourceLocation("amalgam:yellow_carbonite_on"), event);
		registerBlock(YELLOW_DECORATIVE_CARBONITE, new ResourceLocation("amalgam:yellow_decorative_carbonite"), event);
		registerBlock(LIME_CARBONITE, new ResourceLocation("amalgam:lime_carbonite"), event);
		registerBlock(LIME_CARBONITE_OFF, new ResourceLocation("amalgam:lime_carbonite_off"), event);
		registerBlock(LIME_CARBONITE_ON, new ResourceLocation("amalgam:lime_carbonite_on"), event);
		registerBlock(LIME_DECORATIVE_CARBONITE, new ResourceLocation("amalgam:lime_decorative_carbonite"), event);
		registerBlock(PINK_CARBONITE, new ResourceLocation("amalgam:pink_carbonite"), event);
		registerBlock(PINK_CARBONITE_OFF, new ResourceLocation("amalgam:pink_carbonite_off"), event);
		registerBlock(PINK_CARBONITE_ON, new ResourceLocation("amalgam:pink_carbonite_on"), event);
		registerBlock(PINK_DECORATIVE_CARBONITE, new ResourceLocation("amalgam:pink_decorative_carbonite"), event);
		registerBlock(GRAY_CARBONITE, new ResourceLocation("amalgam:gray_carbonite"), event);
		registerBlock(GRAY_CARBONITE_OFF, new ResourceLocation("amalgam:gray_carbonite_off"), event);
		registerBlock(GRAY_CARBONITE_ON, new ResourceLocation("amalgam:gray_carbonite_on"), event);
		registerBlock(GRAY_DECORATIVE_CARBONITE, new ResourceLocation("amalgam:gray_decorative_carbonite"), event);
		registerBlock(SILVER_CARBONITE, new ResourceLocation("amalgam:silver_carbonite"), event);
		registerBlock(SILVER_CARBONITE_OFF, new ResourceLocation("amalgam:silver_carbonite_off"), event);
		registerBlock(SILVER_CARBONITE_ON, new ResourceLocation("amalgam:silver_carbonite_on"), event);
		registerBlock(SILVER_DECORATIVE_CARBONITE, new ResourceLocation("amalgam:silver_decorative_carbonite"), event);
		registerBlock(CYAN_CARBONITE, new ResourceLocation("amalgam:cyan_carbonite"), event);
		registerBlock(CYAN_CARBONITE_OFF, new ResourceLocation("amalgam:cyan_carbonite_off"), event);
		registerBlock(CYAN_CARBONITE_ON, new ResourceLocation("amalgam:cyan_carbonite_on"), event);
		registerBlock(CYAN_DECORATIVE_CARBONITE, new ResourceLocation("amalgam:cyan_decorative_carbonite"), event);
		registerBlock(PURPLE_CARBONITE, new ResourceLocation("amalgam:purple_carbonite"), event);
		registerBlock(PURPLE_CARBONITE_OFF, new ResourceLocation("amalgam:purple_carbonite_off"), event);
		registerBlock(PURPLE_CARBONITE_ON, new ResourceLocation("amalgam:purple_carbonite_on"), event);
		registerBlock(PURPLE_DECORATIVE_CARBONITE, new ResourceLocation("amalgam:purple_decorative_carbonite"), event);
		registerBlock(BLUE_CARBONITE, new ResourceLocation("amalgam:blue_carbonite"), event);
		registerBlock(BLUE_CARBONITE_OFF, new ResourceLocation("amalgam:blue_carbonite_off"), event);
		registerBlock(BLUE_CARBONITE_ON, new ResourceLocation("amalgam:blue_carbonite_on"), event);
		registerBlock(BLUE_DECORATIVE_CARBONITE, new ResourceLocation("amalgam:blue_decorative_carbonite"), event);
		registerBlock(BROWN_CARBONITE, new ResourceLocation("amalgam:brown_carbonite"), event);
		registerBlock(BROWN_CARBONITE_OFF, new ResourceLocation("amalgam:brown_carbonite_off"), event);
		registerBlock(BROWN_CARBONITE_ON, new ResourceLocation("amalgam:brown_carbonite_on"), event);
		registerBlock(BROWN_DECORATIVE_CARBONITE, new ResourceLocation("amalgam:brown_decorative_carbonite"), event);
		registerBlock(GREEN_CARBONITE, new ResourceLocation("amalgam:green_carbonite"), event);
		registerBlock(GREEN_CARBONITE_OFF, new ResourceLocation("amalgam:green_carbonite_off"), event);
		registerBlock(GREEN_CARBONITE_ON, new ResourceLocation("amalgam:green_carbonite_on"), event);
		registerBlock(GREEN_DECORATIVE_CARBONITE, new ResourceLocation("amalgam:green_decorative_carbonite"), event);
		registerBlock(RED_CARBONITE, new ResourceLocation("amalgam:red_carbonite"), event);
		registerBlock(RED_CARBONITE_OFF, new ResourceLocation("amalgam:red_carbonite_off"), event);
		registerBlock(RED_CARBONITE_ON, new ResourceLocation("amalgam:red_carbonite_on"), event);
		registerBlock(RED_DECORATIVE_CARBONITE, new ResourceLocation("amalgam:red_decorative_carbonite"), event);
		registerBlock(BLACK_CARBONITE, new ResourceLocation("amalgam:black_carbonite"), event);
		registerBlock(BLACK_CARBONITE_OFF, new ResourceLocation("amalgam:black_carbonite_off"), event);
		registerBlock(BLACK_CARBONITE_ON, new ResourceLocation("amalgam:black_carbonite_on"), event);
		registerBlock(BLACK_DECORATIVE_CARBONITE, new ResourceLocation("amalgam:black_decorative_carbonite"), event);
	}
	public static void registerOre(Block block, ResourceLocation location, RegistryEvent.Register<Block> event, String... ores) {
		registerBlock(block, location, event);
		for (int i = 0; i < ores.length; ++i) {
			OreDictionary.registerOre(ores[i], ITEMS.get(ITEMS.size() - 1));
		}
	}
	public static void registerBlock(Block block, ResourceLocation location, RegistryEvent.Register<Block> event, String...meta) {
		event.getRegistry().register(block.setRegistryName(location));
		ITEMS.add(new ItemBlock(block).setRegistryName(location));
	}
}