package mod.amalgam.init;

import mod.akrivus.kagic.init.ModItems;
import mod.amalgam.gem.EntityAgate;
import mod.amalgam.gem.EntityAmethyst;
import mod.amalgam.gem.EntityAquaAuraQuartz;
import mod.amalgam.gem.EntityAquamarine;
import mod.amalgam.gem.EntityBismuth;
import mod.amalgam.gem.EntityCarnelian;
import mod.amalgam.gem.EntityCitrine;
import mod.amalgam.gem.EntityEmerald;
import mod.amalgam.gem.EntityEnderPearl;
import mod.amalgam.gem.EntityHessonite;
import mod.amalgam.gem.EntityJasper;
import mod.amalgam.gem.EntityLapisLazuli;
import mod.amalgam.gem.EntityNacre;
import mod.amalgam.gem.EntityNephrite;
import mod.amalgam.gem.EntityPearl;
import mod.amalgam.gem.EntityPeridot;
import mod.amalgam.gem.EntityPyrite;
import mod.amalgam.gem.EntityRoseQuartz;
import mod.amalgam.gem.EntityRuby;
import mod.amalgam.gem.EntityRutile;
import mod.amalgam.gem.EntitySapphire;
import mod.amalgam.gem.EntityTopaz;
import mod.amalgam.gem.EntityWatermelonTourmaline;
import mod.amalgam.gem.EntityZircon;
import mod.amalgam.items.ItemColoredAmalgamGem;
import mod.amalgam.items.ItemConnieBracelet;
import mod.amalgam.items.ItemDebugStaff;
import mod.amalgam.items.ItemGemDestabilizer;
import mod.amalgam.items.ItemAmalgamGem;
import mod.amalgam.items.ItemGemShard;
import mod.amalgam.items.ItemStevenStone;
import net.minecraft.client.renderer.block.model.ModelResourceLocation;
import net.minecraft.item.Item;
import net.minecraft.util.ResourceLocation;
import net.minecraftforge.client.model.ModelLoader;
import net.minecraftforge.event.RegistryEvent;
import net.minecraftforge.fml.common.FMLCommonHandler;
import net.minecraftforge.fml.relauncher.Side;

public class AmItems {
	public static final ItemAmalgamGem AGATE_GEM = new ItemColoredAmalgamGem(EntityAgate.class, "agate");
	public static final ItemAmalgamGem CRACKED_AGATE_GEM = new ItemColoredAmalgamGem(EntityAgate.class, "agate", true);
	public static final ItemAmalgamGem AMETHYST_GEM = new ItemAmalgamGem(EntityAmethyst.class, "amethyst");
	public static final ItemAmalgamGem CRACKED_AMETHYST_GEM = new ItemAmalgamGem(EntityAmethyst.class, "amethyst", true);
	public static final ItemAmalgamGem AQUA_AURA_QUARTZ_GEM = new ItemAmalgamGem(EntityAquaAuraQuartz.class, "aqua_aura_quartz");
	public static final ItemAmalgamGem CRACKED_AQUA_AURA_QUARTZ_GEM = new ItemAmalgamGem(EntityAquaAuraQuartz.class, "aqua_aura_quartz", true);
	public static final ItemAmalgamGem AQUAMARINE_GEM = new ItemAmalgamGem(EntityAquamarine.class, "aquamarine");
	public static final ItemAmalgamGem CRACKED_AQUAMARINE_GEM = new ItemAmalgamGem(EntityAquamarine.class, "aquamarine", true);
	public static final ItemAmalgamGem BISMUTH_GEM = new ItemAmalgamGem(EntityBismuth.class, "bismuth");
	public static final ItemAmalgamGem CRACKED_BISMUTH_GEM = new ItemAmalgamGem(EntityBismuth.class, "bismuth", true);
	public static final ItemAmalgamGem CARNELIAN_GEM = new ItemAmalgamGem(EntityCarnelian.class, "carnelian");
	public static final ItemAmalgamGem CRACKED_CARNELIAN_GEM = new ItemAmalgamGem(EntityCarnelian.class, "carnelian", true);
	public static final ItemAmalgamGem AMETRINE_GEM = new ItemAmalgamGem(EntityCitrine.class, "ametrine");
	public static final ItemAmalgamGem CRACKED_AMETRINE_GEM = new ItemAmalgamGem(EntityCitrine.class, "ametrine", true);
	public static final ItemAmalgamGem CITRINE_GEM = new ItemAmalgamGem(EntityCitrine.class, "citrine");
	public static final ItemAmalgamGem CRACKED_CITRINE_GEM = new ItemAmalgamGem(EntityCitrine.class, "citrine", true);
	public static final ItemAmalgamGem EMERALD_GEM = new ItemAmalgamGem(EntityEmerald.class, "emerald");
	public static final ItemAmalgamGem CRACKED_EMERALD_GEM = new ItemAmalgamGem(EntityEmerald.class, "emerald", true);
	public static final ItemAmalgamGem ENDER_PEARL_GEM = new ItemAmalgamGem(EntityEnderPearl.class, "ender_pearl");
	public static final ItemAmalgamGem CRACKED_ENDER_PEARL_GEM = new ItemAmalgamGem(EntityEnderPearl.class, "ender_pearl", true);
	public static final ItemAmalgamGem HESSONITE_GEM = new ItemAmalgamGem(EntityHessonite.class, "hessonite");
	public static final ItemAmalgamGem CRACKED_HESSONITE_GEM = new ItemAmalgamGem(EntityHessonite.class, "hessonite", true);
	public static final ItemAmalgamGem NOREENA_JASPER_GEM = new ItemAmalgamGem(EntityJasper.class, "noreena_jasper");
	public static final ItemAmalgamGem CRACKED_NOREENA_JASPER_GEM = new ItemAmalgamGem(EntityJasper.class, "noreena_jasper", true);
	public static final ItemAmalgamGem OCEAN_JASPER_GEM = new ItemAmalgamGem(EntityJasper.class, "ocean_jasper");
	public static final ItemAmalgamGem CRACKED_OCEAN_JASPER_GEM = new ItemAmalgamGem(EntityJasper.class, "ocean_jasper", true);
	public static final ItemAmalgamGem BIGGS_JASPER_GEM = new ItemAmalgamGem(EntityJasper.class, "biggs_jasper");
	public static final ItemAmalgamGem CRACKED_BIGGS_JASPER_GEM = new ItemAmalgamGem(EntityJasper.class, "biggs_jasper", true);
	public static final ItemAmalgamGem GREEN_JASPER_GEM = new ItemAmalgamGem(EntityJasper.class, "green_jasper");
	public static final ItemAmalgamGem CRACKED_GREEN_JASPER_GEM = new ItemAmalgamGem(EntityJasper.class, "green_jasper", true);
	public static final ItemAmalgamGem ROYAL_PLUME_JASPER_GEM = new ItemAmalgamGem(EntityJasper.class, "royal_plume_jasper");
	public static final ItemAmalgamGem CRACKED_ROYAL_PLUME_JASPER_GEM = new ItemAmalgamGem(EntityJasper.class, "royal_plume_jasper", true);
	public static final ItemAmalgamGem PICTURE_JASPER_GEM = new ItemAmalgamGem(EntityJasper.class, "picture_jasper");
	public static final ItemAmalgamGem CRACKED_PICTURE_JASPER_GEM = new ItemAmalgamGem(EntityJasper.class, "picture_jasper", true);
	public static final ItemAmalgamGem FLAME_JASPER_GEM = new ItemAmalgamGem(EntityJasper.class, "flame_jasper");
	public static final ItemAmalgamGem CRACKED_FLAME_JASPER_GEM = new ItemAmalgamGem(EntityJasper.class, "flame_jasper", true);
	public static final ItemAmalgamGem BRUNEAU_JASPER_GEM = new ItemAmalgamGem(EntityJasper.class, "bruneau_jasper");
	public static final ItemAmalgamGem CRACKED_BRUNEAU_JASPER_GEM = new ItemAmalgamGem(EntityJasper.class, "bruneau_jasper", true);
	public static final ItemAmalgamGem ZEBRA_JASPER_GEM = new ItemAmalgamGem(EntityJasper.class, "candy_cane_jasper");
	public static final ItemAmalgamGem CRACKED_ZEBRA_JASPER_GEM = new ItemAmalgamGem(EntityJasper.class, "candy_cane_jasper", true);
	public static final ItemAmalgamGem LAPIS_LAZULI_GEM = new ItemAmalgamGem(EntityLapisLazuli.class, "lapis_lazuli");
	public static final ItemAmalgamGem CRACKED_LAPIS_LAZULI_GEM = new ItemAmalgamGem(EntityLapisLazuli.class, "lapis_lazuli", true);
	public static final ItemAmalgamGem NACRE_GEM = new ItemAmalgamGem(EntityNacre.class, "nacre");
	public static final ItemAmalgamGem CRACKED_NACRE_GEM = new ItemAmalgamGem(EntityNacre.class, "nacre", true);
	public static final ItemAmalgamGem PRIME_NEPHRITE_GEM = new ItemAmalgamGem(EntityNephrite.class, "prime_nephrite");
	public static final ItemAmalgamGem CRACKED_PRIME_NEPHRITE_GEM = new ItemAmalgamGem(EntityNephrite.class, "prime_nephrite", true);
	public static final ItemAmalgamGem NEPHRITE_GEM = new ItemAmalgamGem(EntityNephrite.class, "nephrite");
	public static final ItemAmalgamGem CRACKED_NEPHRITE_GEM = new ItemAmalgamGem(EntityNephrite.class, "nephrite", true);
	public static final ItemAmalgamGem PEARL_GEM = new ItemColoredAmalgamGem(EntityPearl.class, "pearl");
	public static final ItemAmalgamGem CRACKED_PEARL_GEM = new ItemColoredAmalgamGem(EntityPearl.class, "pearl", true);
	public static final ItemAmalgamGem PERIDOT_GEM = new ItemAmalgamGem(EntityPeridot.class, "peridot");
	public static final ItemAmalgamGem CRACKED_PERIDOT_GEM = new ItemAmalgamGem(EntityPeridot.class, "peridot", true);
	public static final ItemAmalgamGem PYRITE_GEM = new ItemAmalgamGem(EntityPyrite.class, "pyrite");
	public static final ItemAmalgamGem CRACKED_PYRITE_GEM = new ItemAmalgamGem(EntityPyrite.class, "pyrite", true);
	public static final ItemAmalgamGem ROSE_QUARTZ_GEM = new ItemAmalgamGem(EntityRoseQuartz.class, "rose_quartz");
	public static final ItemAmalgamGem CRACKED_ROSE_QUARTZ_GEM = new ItemAmalgamGem(EntityRoseQuartz.class, "rose_quartz", true);
	public static final ItemAmalgamGem RUBY_GEM = new ItemAmalgamGem(EntityRuby.class, "ruby");
	public static final ItemAmalgamGem CRACKED_RUBY_GEM = new ItemAmalgamGem(EntityRuby.class, "ruby", true);
	public static final ItemAmalgamGem RUTILE_GEM = new ItemAmalgamGem(EntityRutile.class, "rutile");
	public static final ItemAmalgamGem CRACKED_RUTILE_GEM = new ItemAmalgamGem(EntityRutile.class, "rutile", true);
	public static final ItemAmalgamGem SAPPHIRE_GEM = new ItemColoredAmalgamGem(EntitySapphire.class, "sapphire");
	public static final ItemAmalgamGem CRACKED_SAPPHIRE_GEM = new ItemColoredAmalgamGem(EntitySapphire.class, "sapphire", true);
	public static final ItemAmalgamGem TOPAZ_GEM = new ItemAmalgamGem(EntityTopaz.class, "topaz");
	public static final ItemAmalgamGem CRACKED_TOPAZ_GEM = new ItemAmalgamGem(EntityTopaz.class, "topaz", true);
	public static final ItemAmalgamGem WATERMELON_TOURMALINE_GEM = new ItemAmalgamGem(EntityWatermelonTourmaline.class, "watermelon_tourmaline");
	public static final ItemAmalgamGem CRACKED_WATERMELON_TOURMALINE_GEM = new ItemAmalgamGem(EntityWatermelonTourmaline.class, "watermelon_tourmaline", true);
	public static final ItemAmalgamGem ZIRCON_GEM = new ItemColoredAmalgamGem(EntityZircon.class, "zircon");
	public static final ItemAmalgamGem CRACKED_ZIRCON_GEM = new ItemColoredAmalgamGem(EntityZircon.class, "zircon", true);
	
	public static final ItemStevenStone STEVEN_GEM = new ItemStevenStone();
	public static final ItemConnieBracelet CONNIE_BRACELET = new ItemConnieBracelet();
	public static final ItemDebugStaff DEBUG_STAFF = new ItemDebugStaff();

	public static final ItemGemDestabilizer WHITE_GEM_DESTABILIZER = new ItemGemDestabilizer(AmGems.BASIC_WHITE);
	public static final ItemGemDestabilizer ORANGE_GEM_DESTABILIZER = new ItemGemDestabilizer(AmGems.BASIC_ORANGE);
	public static final ItemGemDestabilizer MAGENTA_GEM_DESTABILIZER = new ItemGemDestabilizer(AmGems.BASIC_MAGENTA);
	public static final ItemGemDestabilizer LIGHT_BLUE_GEM_DESTABILIZER = new ItemGemDestabilizer(AmGems.BASIC_LIGHT_BLUE);
	public static final ItemGemDestabilizer YELLOW_GEM_DESTABILIZER = new ItemGemDestabilizer(AmGems.BASIC_YELLOW);
	public static final ItemGemDestabilizer LIME_GEM_DESTABILIZER = new ItemGemDestabilizer(AmGems.BASIC_LIME);
	public static final ItemGemDestabilizer PINK_GEM_DESTABILIZER = new ItemGemDestabilizer(AmGems.BASIC_PINK);
	public static final ItemGemDestabilizer GRAY_GEM_DESTABILIZER = new ItemGemDestabilizer(AmGems.BASIC_GRAY);
	public static final ItemGemDestabilizer SILVER_GEM_DESTABILIZER = new ItemGemDestabilizer(AmGems.BASIC_SILVER);
	public static final ItemGemDestabilizer CYAN_GEM_DESTABILIZER = new ItemGemDestabilizer(AmGems.BASIC_CYAN);
	public static final ItemGemDestabilizer PURPLE_GEM_DESTABILIZER = new ItemGemDestabilizer(AmGems.BASIC_PURPLE);
	public static final ItemGemDestabilizer BLUE_GEM_DESTABILIZER = new ItemGemDestabilizer(AmGems.BASIC_BLUE);
	public static final ItemGemDestabilizer BROWN_GEM_DESTABILIZER = new ItemGemDestabilizer(AmGems.BASIC_BROWN);
	public static final ItemGemDestabilizer GREEN_GEM_DESTABILIZER = new ItemGemDestabilizer(AmGems.BASIC_GREEN);
	public static final ItemGemDestabilizer RED_GEM_DESTABILIZER = new ItemGemDestabilizer(AmGems.BASIC_RED);
	public static final ItemGemDestabilizer BLACK_GEM_DESTABILIZER = new ItemGemDestabilizer(AmGems.BASIC_BLACK);
	
	public static final ItemGemShard WHITE_GEM_SHARD = new ItemGemShard(0);
	public static final ItemGemShard ORANGE_GEM_SHARD = new ItemGemShard(1);
	public static final ItemGemShard MAGENTA_GEM_SHARD = new ItemGemShard(2);
	public static final ItemGemShard LIGHT_BLUE_GEM_SHARD = new ItemGemShard(3);
	public static final ItemGemShard YELLOW_GEM_SHARD = new ItemGemShard(4);
	public static final ItemGemShard LIME_GEM_SHARD = new ItemGemShard(5);
	public static final ItemGemShard PINK_GEM_SHARD = new ItemGemShard(6);
	public static final ItemGemShard GRAY_GEM_SHARD = new ItemGemShard(7);
	public static final ItemGemShard SILVER_GEM_SHARD = new ItemGemShard(8);
	public static final ItemGemShard CYAN_GEM_SHARD = new ItemGemShard(9);
	public static final ItemGemShard PURPLE_GEM_SHARD = new ItemGemShard(10);
	public static final ItemGemShard BLUE_GEM_SHARD = new ItemGemShard(11);
	public static final ItemGemShard BROWN_GEM_SHARD = new ItemGemShard(12);
	public static final ItemGemShard GREEN_GEM_SHARD = new ItemGemShard(13);
	public static final ItemGemShard RED_GEM_SHARD = new ItemGemShard(14);
	public static final ItemGemShard BLACK_GEM_SHARD = new ItemGemShard(15);
	
	public static void register(RegistryEvent.Register<Item> event) {
		registerGemItem(AGATE_GEM, CRACKED_AGATE_GEM, new ResourceLocation("amalgam:agate_gem"), event);
		registerGemItem(AMETHYST_GEM, CRACKED_AMETHYST_GEM, new ResourceLocation("amalgam:amethyst_gem"), event);
		registerGemItem(AQUA_AURA_QUARTZ_GEM, CRACKED_AQUA_AURA_QUARTZ_GEM, new ResourceLocation("amalgam:aqua_aura_quartz_gem"), event);
		registerGemItem(AQUAMARINE_GEM, CRACKED_AQUAMARINE_GEM, new ResourceLocation("amalgam:aquamarine_gem"), event);
		registerGemItem(BISMUTH_GEM, CRACKED_BISMUTH_GEM, new ResourceLocation("amalgam:bismuth_gem"), event);
		registerGemItem(CARNELIAN_GEM, CRACKED_CARNELIAN_GEM, new ResourceLocation("amalgam:carnelian_gem"), event);
		registerGemItem(AMETRINE_GEM, CRACKED_AMETRINE_GEM, new ResourceLocation("amalgam:ametrine_gem"), event);
		registerGemItem(CITRINE_GEM, CRACKED_CITRINE_GEM, new ResourceLocation("amalgam:citrine_gem"), event);
		registerGemItem(EMERALD_GEM, CRACKED_EMERALD_GEM, new ResourceLocation("amalgam:emerald_gem"), event);
		registerGemItem(ENDER_PEARL_GEM, CRACKED_ENDER_PEARL_GEM, new ResourceLocation("amalgam:ender_pearl_gem"), event);
		registerGemItem(HESSONITE_GEM, CRACKED_HESSONITE_GEM, new ResourceLocation("amalgam:hessonite_gem"), event);
		registerGemItem(NOREENA_JASPER_GEM, CRACKED_NOREENA_JASPER_GEM, new ResourceLocation("amalgam:noreena_jasper_gem"), event);
		registerGemItem(OCEAN_JASPER_GEM, CRACKED_OCEAN_JASPER_GEM, new ResourceLocation("amalgam:ocean_jasper_gem"), event);
		registerGemItem(BIGGS_JASPER_GEM, CRACKED_BIGGS_JASPER_GEM, new ResourceLocation("amalgam:biggs_jasper_gem"), event);
		registerGemItem(GREEN_JASPER_GEM, CRACKED_GREEN_JASPER_GEM, new ResourceLocation("amalgam:green_jasper_gem"), event);
		registerGemItem(ROYAL_PLUME_JASPER_GEM, CRACKED_ROYAL_PLUME_JASPER_GEM, new ResourceLocation("amalgam:royal_plume_jasper_gem"), event);
		registerGemItem(PICTURE_JASPER_GEM, CRACKED_PICTURE_JASPER_GEM, new ResourceLocation("amalgam:picture_jasper_gem"), event);
		registerGemItem(FLAME_JASPER_GEM, CRACKED_FLAME_JASPER_GEM, new ResourceLocation("amalgam:flame_jasper_gem"), event);
		registerGemItem(BRUNEAU_JASPER_GEM, CRACKED_BRUNEAU_JASPER_GEM, new ResourceLocation("amalgam:bruneau_jasper_gem"), event);
		registerGemItem(ZEBRA_JASPER_GEM, CRACKED_ZEBRA_JASPER_GEM, new ResourceLocation("amalgam:zebra_jasper_gem"), event);
		registerGemItem(LAPIS_LAZULI_GEM, CRACKED_LAPIS_LAZULI_GEM, new ResourceLocation("amalgam:lapis_lazuli_gem"), event);
		registerGemItem(NACRE_GEM, CRACKED_NACRE_GEM, new ResourceLocation("amalgam:nacre_gem"), event);
		registerGemItem(PRIME_NEPHRITE_GEM, CRACKED_PRIME_NEPHRITE_GEM, new ResourceLocation("amalgam:prime_nephrite_gem"), event);
		registerGemItem(NEPHRITE_GEM, CRACKED_NEPHRITE_GEM, new ResourceLocation("amalgam:nephrite_gem"), event);
		registerGemItem(PEARL_GEM, CRACKED_PEARL_GEM, new ResourceLocation("amalgam:pearl_gem"), event);
		registerGemItem(PERIDOT_GEM, CRACKED_PERIDOT_GEM, new ResourceLocation("amalgam:peridot_gem"), event);
		registerGemItem(PYRITE_GEM, CRACKED_PYRITE_GEM, new ResourceLocation("amalgam:pyrite_gem"), event);
		registerGemItem(ROSE_QUARTZ_GEM, CRACKED_ROSE_QUARTZ_GEM, new ResourceLocation("amalgam:rose_quartz_gem"), event);
		registerGemItem(RUBY_GEM, CRACKED_RUBY_GEM, new ResourceLocation("amalgam:ruby_gem"), event);
		registerGemItem(RUTILE_GEM, CRACKED_RUTILE_GEM, new ResourceLocation("amalgam:rutile_gem"), event);
		registerGemItem(SAPPHIRE_GEM, CRACKED_SAPPHIRE_GEM, new ResourceLocation("amalgam:sapphire_gem"), event);
		registerGemItem(TOPAZ_GEM, CRACKED_TOPAZ_GEM, new ResourceLocation("amalgam:topaz_gem"), event);
		registerGemItem(WATERMELON_TOURMALINE_GEM, CRACKED_WATERMELON_TOURMALINE_GEM, new ResourceLocation("amalgam:watermelon_tourmaline_gem"), event);
		registerGemItem(ZIRCON_GEM, CRACKED_ZIRCON_GEM, new ResourceLocation("amalgam:zircon_gem"), event);
		
		registerItem(WHITE_GEM_DESTABILIZER, new ResourceLocation("amalgam:white_gem_destabilizer"), event);
		registerItem(ORANGE_GEM_DESTABILIZER, new ResourceLocation("amalgam:orange_gem_destabilizer"), event);
		registerItem(MAGENTA_GEM_DESTABILIZER, new ResourceLocation("amalgam:magenta_gem_destabilizer"), event);
		registerItem(LIGHT_BLUE_GEM_DESTABILIZER, new ResourceLocation("amalgam:light_blue_gem_destabilizer"), event);
		registerItem(YELLOW_GEM_DESTABILIZER, new ResourceLocation("amalgam:yellow_gem_destabilizer"), event);
		registerItem(LIME_GEM_DESTABILIZER, new ResourceLocation("amalgam:lime_gem_destabilizer"), event);
		registerItem(PINK_GEM_DESTABILIZER, new ResourceLocation("amalgam:pink_gem_destabilizer"), event);
		registerItem(GRAY_GEM_DESTABILIZER, new ResourceLocation("amalgam:gray_gem_destabilizer"), event);
		registerItem(SILVER_GEM_DESTABILIZER, new ResourceLocation("amalgam:silver_gem_destabilizer"), event);
		registerItem(CYAN_GEM_DESTABILIZER, new ResourceLocation("amalgam:cyan_gem_destabilizer"), event);
		registerItem(PURPLE_GEM_DESTABILIZER, new ResourceLocation("amalgam:purple_gem_destabilizer"), event);
		registerItem(BLUE_GEM_DESTABILIZER, new ResourceLocation("amalgam:blue_gem_destabilizer"), event);
		registerItem(BROWN_GEM_DESTABILIZER, new ResourceLocation("amalgam:brown_gem_destabilizer"), event);
		registerItem(GREEN_GEM_DESTABILIZER, new ResourceLocation("amalgam:green_gem_destabilizer"), event);
		registerItem(RED_GEM_DESTABILIZER, new ResourceLocation("amalgam:red_gem_destabilizer"), event);
		registerItem(BLACK_GEM_DESTABILIZER, new ResourceLocation("amalgam:black_gem_destabilizer"), event);
		
		registerItem(WHITE_GEM_SHARD, new ResourceLocation("amalgam:white_gem_shard"), event);
		registerItem(ORANGE_GEM_SHARD, new ResourceLocation("amalgam:orange_gem_shard"), event);
		registerItem(MAGENTA_GEM_SHARD, new ResourceLocation("amalgam:magenta_gem_shard"), event);
		registerItem(LIGHT_BLUE_GEM_SHARD, new ResourceLocation("amalgam:light_blue_gem_shard"), event);
		registerItem(YELLOW_GEM_SHARD, new ResourceLocation("amalgam:yellow_gem_shard"), event);
		registerItem(LIME_GEM_SHARD, new ResourceLocation("amalgam:lime_gem_shard"), event);
		registerItem(PINK_GEM_SHARD, new ResourceLocation("amalgam:pink_gem_shard"), event);
		registerItem(GRAY_GEM_SHARD, new ResourceLocation("amalgam:gray_gem_shard"), event);
		registerItem(SILVER_GEM_SHARD, new ResourceLocation("amalgam:silver_gem_shard"), event);
		registerItem(CYAN_GEM_SHARD, new ResourceLocation("amalgam:cyan_gem_shard"), event);
		registerItem(PURPLE_GEM_SHARD, new ResourceLocation("amalgam:purple_gem_shard"), event);
		registerItem(BLUE_GEM_SHARD, new ResourceLocation("amalgam:blue_gem_shard"), event);
		registerItem(BROWN_GEM_SHARD, new ResourceLocation("amalgam:brown_gem_shard"), event);
		registerItem(GREEN_GEM_SHARD, new ResourceLocation("amalgam:green_gem_shard"), event);
		registerItem(RED_GEM_SHARD, new ResourceLocation("amalgam:red_gem_shard"), event);
		registerItem(BLACK_GEM_SHARD, new ResourceLocation("amalgam:black_gem_shard"), event);
		
		registerItem(STEVEN_GEM, new ResourceLocation("amalgam:steven_gem"), event);
		registerItem(CONNIE_BRACELET, new ResourceLocation("amalgam:connie_bracelet"), event);
		registerItem(DEBUG_STAFF, new ResourceLocation("amalgam:debug_staff"), event);
		
		for (Item item : AmBlocks.ITEMS) {
			registerItem(item, null, event);
		}
	}
	public static void registerGemItem(ItemAmalgamGem normal, ItemAmalgamGem broken, ResourceLocation name, RegistryEvent.Register<Item> event) {
		AmItems.registerItem(broken, new ResourceLocation(name.getResourcePath(), "cracked_" + name.getResourceDomain()), event);
		AmItems.registerItem(normal, name, event);
		ModItems.GEM_TABLE.put(normal, broken);
		ModItems.GEM_TABLE.put(broken, normal);
	}
	public static void registerItem(Item item, ResourceLocation name, RegistryEvent.Register<Item> event) {
		event.getRegistry().register(name == null ? item : item.setRegistryName(name));
		if (FMLCommonHandler.instance().getSide() == Side.CLIENT) {
			ModelLoader.setCustomModelResourceLocation(item, 0, new ModelResourceLocation(item.getRegistryName(), "inventory"));
		}
	}
}