package mod.amalgam.init;

import mod.akrivus.kagic.init.ModItems;
import mod.amalgam.gem.EntityAgate;
import mod.amalgam.gem.EntityAmethyst;
import mod.amalgam.gem.EntityAquaAuraQuartz;
import mod.amalgam.gem.EntityAquamarine;
import mod.amalgam.gem.EntityBismuth;
import mod.amalgam.gem.EntityCarnelian;
import mod.amalgam.gem.EntityCitrine;
import mod.amalgam.gem.EntityEmerald;
import mod.amalgam.gem.EntityEnderPearl;
import mod.amalgam.gem.EntityHessonite;
import mod.amalgam.gem.EntityJasper;
import mod.amalgam.gem.EntityLapisLazuli;
import mod.amalgam.gem.EntityNacre;
import mod.amalgam.gem.EntityNephrite;
import mod.amalgam.gem.EntityPearl;
import mod.amalgam.gem.EntityPeridot;
import mod.amalgam.gem.EntityPyrite;
import mod.amalgam.gem.EntityRoseQuartz;
import mod.amalgam.gem.EntityRuby;
import mod.amalgam.gem.EntityRutile;
import mod.amalgam.gem.EntitySapphire;
import mod.amalgam.gem.EntityTopaz;
import mod.amalgam.gem.EntityWatermelonTourmaline;
import mod.amalgam.gem.EntityZircon;
import mod.amalgam.items.ItemColoredGem;
import mod.amalgam.items.ItemConnieBracelet;
import mod.amalgam.items.ItemDebugStaff;
import mod.amalgam.items.ItemDestabilizer;
import mod.amalgam.items.ItemGem;
import mod.amalgam.items.ItemShard;
import mod.amalgam.items.ItemStevenStone;
import net.minecraft.client.renderer.block.model.ModelResourceLocation;
import net.minecraft.item.Item;
import net.minecraft.util.ResourceLocation;
import net.minecraftforge.client.model.ModelLoader;
import net.minecraftforge.event.RegistryEvent;
import net.minecraftforge.fml.common.FMLCommonHandler;
import net.minecraftforge.fml.relauncher.Side;

public class AmItems {
	public static final ItemGem AGATE_GEM = new ItemColoredGem(EntityAgate.class, "agate");
	public static final ItemGem AMETHYST_GEM = new ItemGem(EntityAmethyst.class, "amethyst");
	public static final ItemGem AQUA_AURA_QUARTZ_GEM = new ItemGem(EntityAquaAuraQuartz.class, "aqua_aura_quartz");
	public static final ItemGem AQUAMARINE_GEM = new ItemGem(EntityAquamarine.class, "aquamarine");
	public static final ItemGem BISMUTH_GEM = new ItemGem(EntityBismuth.class, "bismuth");
	public static final ItemGem CARNELIAN_GEM = new ItemGem(EntityCarnelian.class, "carnelian");
	public static final ItemGem AMETRINE_GEM = new ItemGem(EntityCitrine.class, "ametrine");
	public static final ItemGem CITRINE_GEM = new ItemGem(EntityCitrine.class, "citrine");
	public static final ItemGem EMERALD_GEM = new ItemGem(EntityEmerald.class, "emerald");
	public static final ItemGem ENDER_PEARL_GEM = new ItemGem(EntityEnderPearl.class, "ender_pearl");
	public static final ItemGem HESSONITE_GEM = new ItemGem(EntityHessonite.class, "hessonite");
	public static final ItemGem NOREENA_JASPER_GEM = new ItemGem(EntityJasper.class, "noreena_jasper");
	public static final ItemGem OCEAN_JASPER_GEM = new ItemGem(EntityJasper.class, "ocean_jasper");
	public static final ItemGem BIGGS_JASPER_GEM = new ItemGem(EntityJasper.class, "biggs_jasper");
	public static final ItemGem GREEN_JASPER_GEM = new ItemGem(EntityJasper.class, "green_jasper");
	public static final ItemGem ROYAL_PLUME_JASPER_GEM = new ItemGem(EntityJasper.class, "royal_plume_jasper");
	public static final ItemGem PICTURE_JASPER_GEM = new ItemGem(EntityJasper.class, "picture_jasper");
	public static final ItemGem FLAME_JASPER_GEM = new ItemGem(EntityJasper.class, "flame_jasper");
	public static final ItemGem BRUNEAU_JASPER_GEM = new ItemGem(EntityJasper.class, "bruneau_jasper");
	public static final ItemGem ZEBRA_JASPER_GEM = new ItemGem(EntityJasper.class, "candy_cane_jasper");
	public static final ItemGem LAPIS_LAZULI_GEM = new ItemGem(EntityLapisLazuli.class, "lapis_lazuli");
	public static final ItemGem NACRE_GEM = new ItemGem(EntityNacre.class, "nacre");
	public static final ItemGem PRIME_NEPHRITE_GEM = new ItemGem(EntityNephrite.class, "prime_nephrite");
	public static final ItemGem NEPHRITE_GEM = new ItemGem(EntityNephrite.class, "nephrite");
	public static final ItemGem PEARL_GEM = new ItemColoredGem(EntityPearl.class, "pearl");
	public static final ItemGem PERIDOT_GEM = new ItemGem(EntityPeridot.class, "peridot");
	public static final ItemGem PYRITE_GEM = new ItemGem(EntityPyrite.class, "pyrite");
	public static final ItemGem ROSE_QUARTZ_GEM = new ItemGem(EntityRoseQuartz.class, "rose_quartz");
	public static final ItemGem RUBY_GEM = new ItemGem(EntityRuby.class, "ruby");
	public static final ItemGem RUTILE_GEM = new ItemGem(EntityRutile.class, "rutile");
	public static final ItemGem SAPPHIRE_GEM = new ItemColoredGem(EntitySapphire.class, "sapphire");
	public static final ItemGem TOPAZ_GEM = new ItemGem(EntityTopaz.class, "topaz");
	public static final ItemGem WATERMELON_TOURMALINE_GEM = new ItemGem(EntityWatermelonTourmaline.class, "watermelon_tourmaline");
	public static final ItemGem ZIRCON_GEM = new ItemColoredGem(EntityZircon.class, "zircon");
	
	public static final ItemGem CRACKED_AGATE_GEM = new ItemColoredGem(EntityAgate.class, "agate", true);
	public static final ItemGem CRACKED_AMETHYST_GEM = new ItemGem(EntityAmethyst.class, "amethyst", true);
	public static final ItemGem CRACKED_AQUA_AURA_QUARTZ_GEM = new ItemGem(EntityAquaAuraQuartz.class, "aqua_aura_quartz", true);
	public static final ItemGem CRACKED_AQUAMARINE_GEM = new ItemGem(EntityAquamarine.class, "aquamarine", true);
	public static final ItemGem CRACKED_BISMUTH_GEM = new ItemGem(EntityBismuth.class, "bismuth", true);
	public static final ItemGem CRACKED_CARNELIAN_GEM = new ItemGem(EntityCarnelian.class, "carnelian", true);
	public static final ItemGem CRACKED_AMETRINE_GEM = new ItemGem(EntityCitrine.class, "ametrine", true);
	public static final ItemGem CRACKED_CITRINE_GEM = new ItemGem(EntityCitrine.class, "citrine", true);
	public static final ItemGem CRACKED_EMERALD_GEM = new ItemGem(EntityEmerald.class, "emerald", true);
	public static final ItemGem CRACKED_ENDER_PEARL_GEM = new ItemGem(EntityEnderPearl.class, "ender_pearl", true);
	public static final ItemGem CRACKED_HESSONITE_GEM = new ItemGem(EntityHessonite.class, "hessonite", true);
	public static final ItemGem CRACKED_NOREENA_JASPER_GEM = new ItemGem(EntityJasper.class, "noreena_jasper", true);
	public static final ItemGem CRACKED_OCEAN_JASPER_GEM = new ItemGem(EntityJasper.class, "ocean_jasper", true);
	public static final ItemGem CRACKED_BIGGS_JASPER_GEM = new ItemGem(EntityJasper.class, "biggs_jasper", true);
	public static final ItemGem CRACKED_GREEN_JASPER_GEM = new ItemGem(EntityJasper.class, "green_jasper", true);
	public static final ItemGem CRACKED_ROYAL_PLUME_JASPER_GEM = new ItemGem(EntityJasper.class, "royal_plume_jasper", true);
	public static final ItemGem CRACKED_PICTURE_JASPER_GEM = new ItemGem(EntityJasper.class, "picture_jasper", true);
	public static final ItemGem CRACKED_FLAME_JASPER_GEM = new ItemGem(EntityJasper.class, "flame_jasper", true);
	public static final ItemGem CRACKED_BRUNEAU_JASPER_GEM = new ItemGem(EntityJasper.class, "bruneau_jasper", true);
	public static final ItemGem CRACKED_ZEBRA_JASPER_GEM = new ItemGem(EntityJasper.class, "candy_cane_jasper", true);
	public static final ItemGem CRACKED_LAPIS_LAZULI_GEM = new ItemGem(EntityLapisLazuli.class, "lapis_lazuli", true);
	public static final ItemGem CRACKED_NACRE_GEM = new ItemGem(EntityNacre.class, "nacre", true);
	public static final ItemGem CRACKED_PRIME_NEPHRITE_GEM = new ItemGem(EntityNephrite.class, "prime_nephrite", true);
	public static final ItemGem CRACKED_NEPHRITE_GEM = new ItemGem(EntityNephrite.class, "nephrite", true);
	public static final ItemGem CRACKED_PEARL_GEM = new ItemColoredGem(EntityPearl.class, "pearl", true);
	public static final ItemGem CRACKED_PERIDOT_GEM = new ItemGem(EntityPeridot.class, "peridot", true);
	public static final ItemGem CRACKED_PYRITE_GEM = new ItemGem(EntityPyrite.class, "pyrite", true);
	public static final ItemGem CRACKED_ROSE_QUARTZ_GEM = new ItemGem(EntityRoseQuartz.class, "rose_quartz", true);
	public static final ItemGem CRACKED_RUBY_GEM = new ItemGem(EntityRuby.class, "ruby", true);
	public static final ItemGem CRACKED_RUTILE_GEM = new ItemGem(EntityRutile.class, "rutile", true);
	public static final ItemGem CRACKED_SAPPHIRE_GEM = new ItemColoredGem(EntitySapphire.class, "sapphire", true);
	public static final ItemGem CRACKED_TOPAZ_GEM = new ItemGem(EntityTopaz.class, "topaz", true);
	public static final ItemGem CRACKED_WATERMELON_TOURMALINE_GEM = new ItemGem(EntityWatermelonTourmaline.class, "watermelon_tourmaline", true);
	public static final ItemGem CRACKED_ZIRCON_GEM = new ItemColoredGem(EntityZircon.class, "zircon", true);
	
	public static final ItemStevenStone STEVEN_GEM = new ItemStevenStone();
	public static final ItemConnieBracelet CONNIE_BRACELET = new ItemConnieBracelet();
	public static final ItemDebugStaff DEBUG_STAFF = new ItemDebugStaff();

	public static final ItemDestabilizer WHITE_DESTABILIZER = new ItemDestabilizer(AmGems.BASIC_WHITE);
	public static final ItemDestabilizer ORANGE_DESTABILIZER = new ItemDestabilizer(AmGems.BASIC_ORANGE);
	public static final ItemDestabilizer MAGENTA_DESTABILIZER = new ItemDestabilizer(AmGems.BASIC_MAGENTA);
	public static final ItemDestabilizer LIGHT_BLUE_DESTABILIZER = new ItemDestabilizer(AmGems.BASIC_LIGHT_BLUE);
	public static final ItemDestabilizer YELLOW_DESTABILIZER = new ItemDestabilizer(AmGems.BASIC_YELLOW);
	public static final ItemDestabilizer LIME_DESTABILIZER = new ItemDestabilizer(AmGems.BASIC_LIME);
	public static final ItemDestabilizer PINK_DESTABILIZER = new ItemDestabilizer(AmGems.BASIC_PINK);
	public static final ItemDestabilizer GRAY_DESTABILIZER = new ItemDestabilizer(AmGems.BASIC_GRAY);
	public static final ItemDestabilizer SILVER_DESTABILIZER = new ItemDestabilizer(AmGems.BASIC_SILVER);
	public static final ItemDestabilizer CYAN_DESTABILIZER = new ItemDestabilizer(AmGems.BASIC_CYAN);
	public static final ItemDestabilizer PURPLE_DESTABILIZER = new ItemDestabilizer(AmGems.BASIC_PURPLE);
	public static final ItemDestabilizer BLUE_DESTABILIZER = new ItemDestabilizer(AmGems.BASIC_BLUE);
	public static final ItemDestabilizer BROWN_DESTABILIZER = new ItemDestabilizer(AmGems.BASIC_BROWN);
	public static final ItemDestabilizer GREEN_DESTABILIZER = new ItemDestabilizer(AmGems.BASIC_GREEN);
	public static final ItemDestabilizer RED_DESTABILIZER = new ItemDestabilizer(AmGems.BASIC_RED);
	public static final ItemDestabilizer BLACK_DESTABILIZER = new ItemDestabilizer(AmGems.BASIC_BLACK);
	
	public static final ItemShard WHITE_GEM_SHARD = new ItemShard(0);
	public static final ItemShard ORANGE_GEM_SHARD = new ItemShard(1);
	public static final ItemShard MAGENTA_GEM_SHARD = new ItemShard(2);
	public static final ItemShard LIGHT_BLUE_GEM_SHARD = new ItemShard(3);
	public static final ItemShard YELLOW_GEM_SHARD = new ItemShard(4);
	public static final ItemShard LIME_GEM_SHARD = new ItemShard(5);
	public static final ItemShard PINK_GEM_SHARD = new ItemShard(6);
	public static final ItemShard GRAY_GEM_SHARD = new ItemShard(7);
	public static final ItemShard LIGHT_GRAY_GEM_SHARD = new ItemShard(8);
	public static final ItemShard CYAN_GEM_SHARD = new ItemShard(9);
	public static final ItemShard PURPLE_GEM_SHARD = new ItemShard(10);
	public static final ItemShard BLUE_GEM_SHARD = new ItemShard(11);
	public static final ItemShard BROWN_GEM_SHARD = new ItemShard(12);
	public static final ItemShard GREEN_GEM_SHARD = new ItemShard(13);
	public static final ItemShard RED_GEM_SHARD = new ItemShard(14);
	public static final ItemShard BLACK_GEM_SHARD = new ItemShard(15);
	
	public static void register(RegistryEvent.Register<Item> event) {
		registerGemItem(AGATE_GEM, CRACKED_AGATE_GEM, new ResourceLocation("amalgam:agate_gem"), event);
		registerGemItem(AMETHYST_GEM, CRACKED_AMETHYST_GEM, new ResourceLocation("amalgam:amethyst_gem"), event);
		registerGemItem(AQUA_AURA_QUARTZ_GEM, CRACKED_AQUA_AURA_QUARTZ_GEM, new ResourceLocation("amalgam:aqua_aura_quartz_gem"), event);
		registerGemItem(AQUAMARINE_GEM, CRACKED_AQUAMARINE_GEM, new ResourceLocation("amalgam:aquamarine_gem"), event);
		registerGemItem(BISMUTH_GEM, CRACKED_BISMUTH_GEM, new ResourceLocation("amalgam:bismuth_gem"), event);
		registerGemItem(CARNELIAN_GEM, CRACKED_CARNELIAN_GEM, new ResourceLocation("amalgam:carnelian_gem"), event);
		registerGemItem(AMETRINE_GEM, CRACKED_AMETRINE_GEM, new ResourceLocation("amalgam:ametrine_gem"), event);
		registerGemItem(CITRINE_GEM, CRACKED_CITRINE_GEM, new ResourceLocation("amalgam:citrine_gem"), event);
		registerGemItem(EMERALD_GEM, CRACKED_EMERALD_GEM, new ResourceLocation("amalgam:emerald_gem"), event);
		registerGemItem(ENDER_PEARL_GEM, CRACKED_ENDER_PEARL_GEM, new ResourceLocation("amalgam:ender_pearl_gem"), event);
		registerGemItem(HESSONITE_GEM, CRACKED_HESSONITE_GEM, new ResourceLocation("amalgam:hessonite_gem"), event);
		registerGemItem(NOREENA_JASPER_GEM, CRACKED_NOREENA_JASPER_GEM, new ResourceLocation("amalgam:noreena_jasper_gem"), event);
		registerGemItem(OCEAN_JASPER_GEM, CRACKED_OCEAN_JASPER_GEM, new ResourceLocation("amalgam:ocean_jasper_gem"), event);
		registerGemItem(BIGGS_JASPER_GEM, CRACKED_BIGGS_JASPER_GEM, new ResourceLocation("amalgam:biggs_jasper_gem"), event);
		registerGemItem(GREEN_JASPER_GEM, CRACKED_GREEN_JASPER_GEM, new ResourceLocation("amalgam:green_jasper_gem"), event);
		registerGemItem(ROYAL_PLUME_JASPER_GEM, CRACKED_ROYAL_PLUME_JASPER_GEM, new ResourceLocation("amalgam:royal_plume_jasper_gem"), event);
		registerGemItem(PICTURE_JASPER_GEM, CRACKED_PICTURE_JASPER_GEM, new ResourceLocation("amalgam:picture_jasper_gem"), event);
		registerGemItem(FLAME_JASPER_GEM, CRACKED_FLAME_JASPER_GEM, new ResourceLocation("amalgam:flame_jasper_gem"), event);
		registerGemItem(BRUNEAU_JASPER_GEM, CRACKED_BRUNEAU_JASPER_GEM, new ResourceLocation("amalgam:bruneau_jasper_gem"), event);
		registerGemItem(ZEBRA_JASPER_GEM, CRACKED_ZEBRA_JASPER_GEM, new ResourceLocation("amalgam:zebra_jasper_gem"), event);
		registerGemItem(LAPIS_LAZULI_GEM, CRACKED_LAPIS_LAZULI_GEM, new ResourceLocation("amalgam:lapis_lazuli_gem"), event);
		registerGemItem(NACRE_GEM, CRACKED_NACRE_GEM, new ResourceLocation("amalgam:nacre_gem"), event);
		registerGemItem(PRIME_NEPHRITE_GEM, CRACKED_PRIME_NEPHRITE_GEM, new ResourceLocation("amalgam:prime_nephrite_gem"), event);
		registerGemItem(NEPHRITE_GEM, CRACKED_NEPHRITE_GEM, new ResourceLocation("amalgam:nephrite_gem"), event);
		registerGemItem(PEARL_GEM, CRACKED_PEARL_GEM, new ResourceLocation("amalgam:pearl_gem"), event);
		registerGemItem(PERIDOT_GEM, CRACKED_PERIDOT_GEM, new ResourceLocation("amalgam:peridot_gem"), event);
		registerGemItem(PYRITE_GEM, CRACKED_PYRITE_GEM, new ResourceLocation("amalgam:pyrite_gem"), event);
		registerGemItem(ROSE_QUARTZ_GEM, CRACKED_ROSE_QUARTZ_GEM, new ResourceLocation("amalgam:rose_quartz_gem"), event);
		registerGemItem(RUBY_GEM, CRACKED_RUBY_GEM, new ResourceLocation("amalgam:ruby_gem"), event);
		registerGemItem(RUTILE_GEM, CRACKED_RUTILE_GEM, new ResourceLocation("amalgam:rutile_gem"), event);
		registerGemItem(SAPPHIRE_GEM, CRACKED_SAPPHIRE_GEM, new ResourceLocation("amalgam:sapphire_gem"), event);
		registerGemItem(TOPAZ_GEM, CRACKED_TOPAZ_GEM, new ResourceLocation("amalgam:topaz_gem"), event);
		registerGemItem(WATERMELON_TOURMALINE_GEM, CRACKED_WATERMELON_TOURMALINE_GEM, new ResourceLocation("amalgam:watermelon_tourmaline_gem"), event);
		registerGemItem(ZIRCON_GEM, CRACKED_ZIRCON_GEM, new ResourceLocation("amalgam:zircon_gem"), event);
		
		ModItems.registerExternalItem(WHITE_DESTABILIZER, "amalgam", event);
		ModItems.registerExternalItem(ORANGE_DESTABILIZER, "amalgam", event);
		ModItems.registerExternalItem(MAGENTA_DESTABILIZER, "amalgam", event);
		ModItems.registerExternalItem(LIGHT_BLUE_DESTABILIZER, "amalgam", event);
		ModItems.registerExternalItem(YELLOW_DESTABILIZER, "amalgam", event);
		ModItems.registerExternalItem(LIME_DESTABILIZER, "amalgam", event);
		ModItems.registerExternalItem(PINK_DESTABILIZER, "amalgam", event);
		ModItems.registerExternalItem(GRAY_DESTABILIZER, "amalgam", event);
		ModItems.registerExternalItem(SILVER_DESTABILIZER, "amalgam", event);
		ModItems.registerExternalItem(CYAN_DESTABILIZER, "amalgam", event);
		ModItems.registerExternalItem(PURPLE_DESTABILIZER, "amalgam", event);
		ModItems.registerExternalItem(BLUE_DESTABILIZER, "amalgam", event);
		ModItems.registerExternalItem(BROWN_DESTABILIZER, "amalgam", event);
		ModItems.registerExternalItem(GREEN_DESTABILIZER, "amalgam", event);
		ModItems.registerExternalItem(RED_DESTABILIZER, "amalgam", event);
		ModItems.registerExternalItem(BLACK_DESTABILIZER, "amalgam", event);
		
		ModItems.registerExternalItem(WHITE_GEM_SHARD, "amalgam", event);
		ModItems.registerExternalItem(ORANGE_GEM_SHARD, "amalgam", event);
		ModItems.registerExternalItem(MAGENTA_GEM_SHARD, "amalgam", event);
		ModItems.registerExternalItem(LIGHT_BLUE_GEM_SHARD, "amalgam", event);
		ModItems.registerExternalItem(YELLOW_GEM_SHARD, "amalgam", event);
		ModItems.registerExternalItem(LIME_GEM_SHARD, "amalgam", event);
		ModItems.registerExternalItem(PINK_GEM_SHARD, "amalgam", event);
		ModItems.registerExternalItem(GRAY_GEM_SHARD, "amalgam", event);
		ModItems.registerExternalItem(LIGHT_GRAY_GEM_SHARD, "amalgam", event);
		ModItems.registerExternalItem(CYAN_GEM_SHARD, "amalgam", event);
		ModItems.registerExternalItem(PURPLE_GEM_SHARD, "amalgam", event);
		ModItems.registerExternalItem(BLUE_GEM_SHARD, "amalgam", event);
		ModItems.registerExternalItem(BROWN_GEM_SHARD, "amalgam", event);
		ModItems.registerExternalItem(GREEN_GEM_SHARD, "amalgam", event);
		ModItems.registerExternalItem(RED_GEM_SHARD, "amalgam", event);
		ModItems.registerExternalItem(BLACK_GEM_SHARD, "amalgam", event);
		
		ModItems.registerExternalItem(STEVEN_GEM, "amalgam", event);
		ModItems.registerExternalItem(CONNIE_BRACELET, "amalgam", event);
		ModItems.registerExternalItem(DEBUG_STAFF, "amalgam", event);
		
		for (Item item : AmBlocks.ITEMS) {
			ModItems.registerExternalItem(item, "amalgam", event);
		}
	}
	public static void registerGemItem(ItemGem normal, ItemGem broken, ResourceLocation name, RegistryEvent.Register<Item> event) {
		AmItems.registerItem(broken, new ResourceLocation(name.getResourcePath(), "cracked_" + name.getResourceDomain()), event);
		AmItems.registerItem(normal, name, event);
		ModItems.GEM_TABLE.put(normal, broken);
		ModItems.GEM_TABLE.put(broken, normal);
	}
	public static void registerItem(Item item, ResourceLocation name, RegistryEvent.Register<Item> event) {
		event.getRegistry().register(item.setRegistryName(name));
		if (FMLCommonHandler.instance().getSide() == Side.CLIENT) {
			ModelLoader.setCustomModelResourceLocation(item, 0, new ModelResourceLocation(item.getRegistryName(), "inventory"));
		}
	}
}
